sunday:
  - hour: 0
    enabled: false
  - hour: 1
    enabled: true
  - hour: 23
    enabled: false
monday:
  - hour: 0
    enabled: true
  - hour: 23
    enabled: false
tuesday:
  - hour: 0
    enabled: false
  - hour: 23
    enabled: true
wednesday:
  - hour: 0
    enabled: true
  - hour: 23
    enabled: true
thursday:
  - hour: 0
    enabled: false
  - hour: 23
    enabled: false
friday:
  - hour: 0
    enabled: true
  - hour: 23
    enabled: true
saturday:
  - hour: 0
    enabled: false
  - hour: 23
    enabled: false
