services:
  schedulerr:
    container_name: schedulerr
    image: ghcr.io/autobrr/schedulerr:latest
    environment:
      - TZ=UTC
    ports:
      - "8585:8585"
    user: 1000:1000
    volumes:
      - "./:/config"